---
title: "My Website"
---

# Librairies

```{r libraries}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
  install.packages("ggplot2")
}
library(ggplot2)
```

# Récupération des données

```{r chargementData}
raw_data <- read.csv("output_file.csv")
```


Définir toutes les données comme caractère (variable qualitative) sauf le salaire

```{r colonnesQualitative}
# Name of the numeric column
numericColumn <- "salaire"

# Convert all columns to character except the numeric column
raw_data[, setdiff(names(raw_data), numericColumn)] <- lapply(raw_data[, setdiff(names(raw_data), numericColumn)], as.character)

raw_data$Date <- as.Date(raw_data$Date)
```

```{r affichageSummaryRawData}
summary(raw_data)
```

# Première étude 

```{r etude1}
boxplot(raw_data$salaire ~ raw_data$Genre)
```


```{r etude2}
boxplot(raw_data$salaire ~ raw_data$annee_optention_diplome)
```

```{r etude3}
boxplot(raw_data$salaire ~ raw_data$type_formation)
```



```{r etude4}
boxplot(raw_data$salaire ~ raw_data$formation)
```







```{r etude5}
boxplot(raw_data$salaire ~ raw_data$situation_actuelle)
```






```{r etude6}
boxplot(raw_data$salaire ~ raw_data$salarie_ou_non)
```



```{r etude7}
boxplot(raw_data$salaire ~ raw_data$nature_du_contrat)
```






Trier les données de durée du cdd avant 
```{r etude8}

ordered_data <- raw_data[order(as.numeric(raw_data$duree_cdd)), ]




boxplot(raw_data$salaire ~ as.numeric(raw_data$duree_cdd), data = ordered_data)
```

```{r etude8}
raw_data$month_group <- cut(as.numeric(raw_data$duree_cdd),
                               breaks = c(0, 6, 12, 24, Inf),
                               labels = c("1-6", "7-12", "13-24", "25+"),
                               right = FALSE)


boxplot(raw_data$salaire ~ raw_data$month_group, data = raw_data)
```


```{r etude9}
boxplot(raw_data$salaire ~ raw_data$emploi_en_france)
```


```{r etude10, warning=FALSE}
median_salaries <- tapply(raw_data$salaire, raw_data$emploi_etranger, median)
median_order <- names(sort(median_salaries))

raw_data$emploi_etranger <- factor(raw_data$emploi_etranger, levels = median_order)



ggplot(raw_data, aes(x = emploi_etranger, y = salaire)) +
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 8)) +
  labs(title = "Salary Distribution by Country", x = "Country", y = "Salary")
```



